### ISSUE TITLE
Possible incomplete installation instructions

### ISSUE THREAD

**Issue by sirwnstn** [DeepWoods/gsuiteRadius#3]
I've followed the directions as listed in the README.  Upon "docker-compose up" I receive an error saying ".../gsuiteRadius/radius/id_rsa.txt" should be created.  I assume the id_rsa.txt file is an ssh private key, which I then create.  Thereafter I receive when running "docker-compose up":

>  tls: Failed reading certificate file "/etc/freeradius/3.0/certs/radius.acme.com.crt"
tls: error:0200100D:system library:fopen:Permission denied
tls: error:20074002:BIO routines:file_ctrl:system lib
tls: error:140DC002:SSL routines:use_certificate_chain_file:system lib
rlm_eap_tls: Failed initializing SSL context
rlm_eap (EAP): Failed to initialise rlm_eap_tls
/etc/freeradius/3.0/mods-enabled/eap[1]: Instantiation failed for module "eap"

Are there missing steps that I must complete before running docker-compose?

**Comment by DeepWoods** [comment]
The included certificates and secrets files such as the Google LDAP certificate and key should be edited in the configuration to use your own specific credentials and domain information.   That said, you should be able to create empty files of all three of the default secrets files and the images would build.  The containers would still crash since the LDAP and EAP configurations aren't complete but you shouldn't be getting a file permissions error.  What OS and version are you running for the docker host?

**Comment by sirwnstn** [comment]
I'm using VMware Photon OS 4.0 as the docker host.  I was able to run [hacor/unifi-freeradius-ldap](https://github.com/hacor/unifi-freeradius-ldap) on it with no problems in the past, so I began comparing the docker-compose.yml's, Dockerfile's, and init scripts between hacor's and yours.   I ran your radius container detached and entered the container.  It seems that you copy the cert files over fine, but the ownerships stay as root.  I made a quick change in the radius Dockerfile line 105: `COPY --chown=freerad:freerad ./certs/ /etc/freeradius/3.0/certs/` and the container started without errors anymore.  I'll leave it up to you to add this change to the repo if you want to or not.  It seems this fix is particular to the OS of my docker host and may not necessarily work for others.
